[package]
name = "directed_acyclic_graph_relaxation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
depth_first_search = { path = "../depth_first_search" }
